### ISSUE TITLE
Spørsmål: Er det støtte for å hente og bekrefte flere kvitteringer samtidig?

### ISSUE THREAD

**Issue by JoakimBor** [difi/sikker-digital-post-klient-java#100]
Hei!
Vi forventer å sende ut en god chunk (750k+) brev gjennom dpi i starten av januar og ønsker derfor å høre om det i dag er støtte for å hente flere kvitteringer om gangen? Slik vi har satt det opp i dag henter vi kun 1 kvittering / sec men vi kommer nok til å skru denne til å bli langt mer greedy ved den store kjøringen - altså hente kvitteringer til det er tomt. Her hadde det vært ønskelig å hente en chunk kvitteringer i steden. Bruker vi evt feil bibliotek?
I dag bruker vi [DigipostMessageSenderFacade.java](https://github.com/difi/sikker-digital-post-klient-java/blob/master/src/main/java/no/difi/sdp/client2/internal/DigipostMessageSenderFacade.java) med hentKvittering() og bekreft()

**Comment by velfundert** [comment]
Hei!

Det er dessverre kun mulig å hente én kvittering av gangen fra Meldingsformidleren.
