### ISSUE TITLE
Tilgang til opprinnelig Forretningskvittering: toString metodene gir ikke ut opprinnelig XML knyttet til en melding

### ISSUE THREAD

**Issue by aberner** [difi/sikker-digital-post-klient-java#14]
Avsendere har behov for enkel tilgang til de opprinnelige Forretningskvitteringene de mottar fra Postkassen. Dette for å kunne lagre/arkivere dette elementet med signaturer.

dette er blant annet knyttet til følgende forbedringsønske: https://github.com/difi/begrep-SikkerDigitalPost/issues/132 
og Avsenders behov for å holde juridiske logger.

Det må legges til en den abstrakte  API klassen: https://github.com/difi/sikker-digital-post-java-klient/blob/master/src/main/java/no/difi/sdp/client/domain/kvittering/ForretningsKvittering.java eventuelt at toString metodene oppdateres til å levere ut XML meldingen fra postkassen urørt.

**Comment by asjafjell** [comment]
@aberner: Er dette fortsatt et behov?

**Comment by aberner** [comment]
@asjafjell enten så bør dette implementeres eller så bør forslaget til @eoftedal dokumenteres slik at det enkelt kan finnes av avsendere.
Det er anbefalt at alle avsendere logger Leveringskvitteringen som et bevis på at forsendelsen er ok.

Dermed så synes jeg at dette burde støttes av klientbibliotektet ut av boksen uten at avsender må gjøre en spesiell konfigurasjon.

**Comment by aberner** [comment]
@tor-kleiberg ref. dagens prat. Leveringskvittering med signaturer er ikke noe som er tilbudt ut av boksen av API'ene i klientbibliotekene.

**Comment by mhoel** [comment]
Som @aberner har vi også et behov for å hente ut kvitteringen i sin helhet med Signaturelementet for å persistere den i vår database. Jeg har innsett at vi kan gjøre det via interceptors på Spring WS template og det er supert at dere tilbyr, men jeg tror det blir mye renere kode om abstraksjonen som returneres fra klienten var oppdatert til å tilby dette. Interceptor er fint for logging, men hvis vi ender opp med å blande databaselaget med interceptors blir forretningsflyten muligens litt rotete.
