### ISSUE TITLE
Opprydning i API rundt ForretningsKvittering

### ISSUE THREAD

**Issue by runeflobakk** [difi/sikker-digital-post-klient-java#27]
Det er en del design-flaws i klassene rundt ForretningsKvittering og EbmsApplikasjonsKvittering.

- [x] metoden `EbmsApplikasjonsKvittering.getKvittering()` merkes som `@Deprecated`. Ref #26  

 `ForretningsKvittering` bør berikes med flere API-metoder for å slippe å hente ut `ForretningsKvittering.applikasjonsKvittering.getStandardBusinessDocument()`:
- [x] metode for å sjekke hva slags type det er (feil, kvittering)
- [x] aksess til `SimpleKvittering`, dersom `ForretningsKvittering.erKvittering()`
- [x] aksess til `SBDFeil`, dersom `ForretningsKvittering.erFeil()`. Lag gjerne også en egen type à la `SimpleKvittering` for å slippe å lekke ut JAXB-genererte typer fra APIet.
- [x]  sjekk om `ApplikasjonsKvitteringBuilder` kan fjernes, ev. merkes `@Deprecated`

**Comment by asjafjell** [comment]
Dette er fikset i [2.1.0](http://search.maven.org/#artifactdetails%7Cno.difi.sdp%7Csikker-digital-post-klient-java%7C2.1.0%7Cjar)
