### ISSUE TITLE
standard varsling som settes opp er i ikke i henhold til det som anbefales for Avsendere som skal varsle

### ISSUE THREAD

**Issue by aberner** [difi/sikker-digital-post-klient-java#29]
I https://github.com/difi/sikker-digital-post-java-klient/blob/master/src/main/java/no/difi/sdp/client/domain/digital_post/EpostVarsel.java er standard at det settes opp ett varsel samtidig som brevet blir tilgjengeliggjort for mottaker.

Avsendere sitt bruk av varslinger er styrt av eForvaltningsforskriften §8a (http://lovdata.no/dokument/SF/forskrift/2004-06-25-988/KAPITTEL_2#%C2%A78) og dokumentert her: http://begrep.difi.no/SikkerDigitalPost/1.2.0/begrep/Varsler

Dersom klientbiblioteket overhode skal ha noe default varslingsinstillinger så bør det være i henhold til eForvaltningsforskriften og dermed være 0,7

Vi har eksempler på virksomheter som har satt opp varsling slik:
- DigitalPost.Builder postBuilder = …
postBuilder.epostVarsel(EpostVarsel.builder(epostadresse, varslingsTekstEpost).build());

Dette har dermed ført til at de har fått varslinger som ikke er i henhold til kravene i forskriften.

Det vil vært svært få, om noen som vil bestille varsling kun ved tilgjengeliggjøring.

**Comment by runeflobakk** [comment]
Er denne endringen OK å release as-is? Det fikser en "bug" som sådan, men dette medfører likefullt en oppførselsendring. Skal det gjøres noe mer seremonielt enn å bare release en ny minor-versjon?

**Comment by aberner** [comment]
@kjorlaug Har du noe forslag til hvordan denne endringen bør versjoneres?

**Comment by aberner** [comment]
Denne endringen må følge opp med en versjonering som viser at ny versjon bryter med eksisterende funksjonalitet. så dette blir vel da en endring av major versjon. eller hva sier du @kjorlaug ?

**Comment by kjorlaug** [comment]
Ser eg må jobbe med responstid :-)

Det har vel strengt tatt ikkje vore landa om vi skal bruke same verjsonering her som i dokumentasjonen. Eg stemmer vel for @runeflobakk sin variant med ein minor release og at dette er ein bugfix. Det hadde vore annarleis om ein ikkje hadde default-verdi og fjerna funksjonen heilt...

**Comment by asjafjell** [comment]
Dette er ikke en fullstendig endring av grensesnitt og masse nye features, så jeg stemmer også for at dette bør være en minor-versjon.

**Comment by kjorlaug** [comment]
Ser at de med fordel kan ta fram @aberner sitt poeng med varsling i dokumentasjonen - står ikkje mykje om varsling i eksempelet der. Som Arne er inne på så er dette sentralt i forskrifta...

**Comment by asjafjell** [comment]
Ser at det tekniske i dette issuet er løst, så lukker denne.
