### ISSUE TITLE
Kan Java-versjon oppdateres til 7?

### ISSUE THREAD

**Issue by runeflobakk** [difi/sikker-digital-post-klient-java#30]
Java 6 begynner å bli gammelt, og vi ser mer og mer tendensen at også mere kritiske biblioteker  begynner å droppe støtte for Java 6. Eksempelvis krever [WSS4J](https://ws.apache.org/wss4j/) minimum Java 7 f.o.m. versjon 2.1.x.

Gjelder #13 fremdeles, at klientbiblioteket må fungere på Java 6? Eller kan minimum Java-versjon oppdateres til versjon 7?

**Comment by aberner** [comment]
Jeg skal ta en sjekk med virksomhetene som bruker biblioteket.

**Comment by aberner** [comment]
følger opp saken, men ikke fått noe tilbakemelding. Avventer svar i neste uke.

**Comment by aberner** [comment]
@runeflobakk Avsendere har behov for at vi støtter java 6 frem til og med 04.2016.
