### ISSUE TITLE
Mulighet for resending av samme melding med samme InstanceIdentifier

### ISSUE THREAD

**Issue by aberner** [difi/sikker-digital-post-klient-java#32]
Dersom en Avsender får en feil i forbindelse med sin sending av digital post så kan det bli behov for å forsøke en resending. For å resende eksakt samme forsendelse må både konversasjonsid og InstanceIdentifier være lik i den opprinnelige forsendelsen og i den etterfølgende resendingen.

Klientbiblioteket støtter ikke at en avsender kan  sette InstanceIdentifier. Den blir generert som en random UUID alltid og det medfører at avsender dermed får en ebms feilmelding tilbake om at det er duplicate conversationid.

eksempel på feilsituasjon hvor denne problemstillingen oppstår:

- Avsender sender digital post
- Meldingsformidler mottar og lagrer ned forsendelsen, svarer med en ok response
- Avsender mottar responsen men har en treighet og klokker som er noe ute av synk slik at de får en exception om at WS-Sec timestamp ikke er gyldig. 

Her er forsendelsen ok levert og vil bli videreformidlet til postkassen, mens Avsender tror at forsendelsen har feilet og vil forsøke å resende.

**Comment by kristianenge** [comment]
Jeg har funnet ut at instanceIdentifier ikke er det eneste som må endres for å få resendingen til å fungere i biblioteket. Endringene som må til går også en del dypere enn klientbiblioteket så må avklare hva det har å si for de andre som bruker samme avhengighetene. 

Estimerer hvor stor denne oppgaven er og når vi kan få bistand og kommer tilbake med svar.

**Comment by kagkarlsson** [comment]
Vi har sett lite på denna issuen, och som @kristianenge nämner har det visat sig att vi måste göra lite större ändringar för att stötta re-sending av SDP-meldingen. 

En förutsättning för att re-sending ska gå ok (dvs ge OK transportkvittering tillbaka) är att man brukar samma message-id (i EBMS-konvolutt) och att digest för body (SDP) och attachment (krypterad AsicE) är identisk, dvs. ger samma digest.

Pga krypteringen så ser vi ingen möjlighet för att det ska gå att generera två krypterade AsicE-packar med identiskt byte-content. Därför blir en förutsättning för re-sending av en SDP-melding att man har tagit vara på den originala AsicE-packen.

Är en sådan ändring acceptabel för att stötta re-sending? @aberner

**Comment by aberner** [comment]
dette gjør at oppgaven blir større/mer omfattende.
Foreslår at vi lar denne ligge til det blir et større/konkret behov for avsendere.

**Comment by aberner** [comment]
denne saken lukkes, da det er relativt omfattende å fikse og samtidig er usikkerhet omkring behovet.
Dersom behovet dukker opp på nytt eller viser seg å være viktig å realisere så åpnes eventuelt arbeidet på nytt.
