### ISSUE TITLE
De siste versjonene som er levert mangler release info i git

### ISSUE THREAD

**Issue by aberner** [difi/sikker-digital-post-klient-java#33]
Det er ikke lagt ut noen releaser ( https://github.com/difi/sikker-digital-post-java-klient/releases) siden versjon 1.1.8.
Dermed har ikke de siste versjonen fått noe realease dokumentasjon og det er vanskeligere å følge med på innholdet i nye versjoner og hvilke som er prereleases/drafts og hvilke som er offiselle nye versjoner.

**Comment by asjafjell** [comment]
Dette er noe som har blitt forsømt i de siste releasene, og vi skal bli bedre på dette i framtiden. Ønsker du at vi lager release notes på gamle, eller er det nok at vi tar tak i det fra nå av?

**Comment by aberner** [comment]
Det bør foreligge release dokumentasjon for alle endringer, også for de gamle som mangler dette.

**Comment by asjafjell** [comment]
Denne er bare glemt lukket. Lukker nå.
