### ISSUE TITLE
Ønsker mulighet for å stoppe requester til feil miljø

### ISSUE THREAD

**Issue by aberner** [difi/sikker-digital-post-klient-java#34]
Vi opplever at flere avsender i sin testing blander mellom det funksjonelle testmiljøet og produksjon.
Klientbiblioteket har informasjon om et sertifikat er et gyldig produksjonssertifikat eller ikke og kan dermed stoppe requestene før de sendes og gi en fornuftig feilmelding/exception tilbake til utvikler/tester.

Klientbiblioteket må ta høyde for følgende ved innføring av en slik mekanisme:
- Det er forskjellige lenker til produksjon for vanlige integrasjon og integrasjon fra norsk helsenett
- Det er forskjellige sertifikater som kan benyttes, både commfides og buypass.

Det er flere måter å sjekke om sertifikatet kan brukes mot produksjonsmiljøet eller ikke.
Det som blir mest korrekt er å sjekke klient sertifikatets policy, her skal det være referanse til en av de følgende OID'ene:
- 2.16.578.1.29.13.1.1.0 (commifdes)
- 2.16.578.1.26.1.3.2 (buypass soft tokens)
- 2.16.578.1.26.1.3.5 (buypass hard tokens)

I test brukes andre sertifikat policer.

referanser til sertifikat policyene til leverandørene:
- Buypass certificate policy: http://www.buypass.no/kundeservice/nedlastingssenter/_attachment/26270?_ts=1505bfe4d20
- Commfides certificate policy: https://www.commfides.com/images/stories/artikler/Installasjon_av_CPN_RootCA_SHA256_Class_3/cn-cp_01_certificate%20policy%20for%20commfides%20sha256%20class3%20enterprise%20certificates.pdf

Denne forbedringen ønskes også i .net klientbiblioteket (https://github.com/difi/sikker-digital-post-klient-dotnet , oppretter tilsvarende sak der, men tenker at det kan spesifiseres opp her først og så realiseres i begge bibliotek).

**Comment by asjafjell** [comment]
Er det slik at det er ønskelig å stoppe sending mot testmiljø med produksjonssertifikat også, @aberner? At dette er tillatt nå er kun av historiske grunner og vi tenker at vi bør stoppe dette også. Er du enig?

**Comment by aberner** [comment]
problemet her er først og fremst at avsender spammer produksjonsmiljøet under sin utvikling/testing, og ikke at en avsender sender til test i stedet for produksjon.
men det er vel riktig slutning at produksjonssertifikater ikke skal brukes mot testmiljøet. Det er vel ikke tillatt i dag eller?

**Comment by asjafjell** [comment]
Her er vi helt enige! Jo, det er faktisk mulig, men dette tenker vi å sette en stopper for i klientbibliotekene. Høres ut som vi er enige i at dette gjelder begge veier, selv om det er viktigst i det tilfellet du skisserer.

**Comment by asjafjell** [comment]
Det er avsendere som gjør dette i dag, @aberner. Skal vi bare slå av støtten for å sende mot test med prodsertifikater eller skal disse informeres først?

**Comment by aberner** [comment]
Hvilke avsendere er det som gjør dette? kan du sende meg en e-post med en liste over de som gjør dette så kan jeg vurdere dette.

**Comment by asjafjell** [comment]
Har du mulighet til å oppdrive dette til Arne, @landro?

**Comment by aberner** [comment]
virksomhetene som bryter med dette vil bli informert og endringen kan realiseres.

**Comment by asjafjell** [comment]
Denne ble implementert i [5.1.0](https://github.com/difi/sikker-digital-post-klient-java/releases/tag/5.1.0)
