### ISSUE TITLE
URL til meldingsformidler bør inneholde org.nummer til avsender

### ISSUE THREAD

**Issue by aberner** [difi/sikker-digital-post-klient-java#35]
Vi ser at det hadde vært fordelaktig om avsender sitt org.nummer hadde vært enkelt tilgjengelig i URL'n brukt mot meldingsformidler. Dette gjør at vi enklere/raskere kan feilsøke og bruke denne informasjonen f.eks. for å begrense/skille trafikken.

forslaget er at url'n endres slik at org.nummeret legges på enden av url'n omtrent slik:

- https://qaoffentlig.meldingsformidler.digipost.no/api/9908:12345678

Det som må avklares er hvilket org.nummer som skal brukes. Er det Databehandler eller Behandlingsansvarlig sitt org.nummer som er best å legge på. Eventuelt begge to.
I utgangspunktet mener jeg at det skal være org.nummeret til databehandler.

eventuelt kan man vurdere noe slikt:

- https://qaoffentlig.meldingsformidler.digipost.no/api/9908:12345678/9908:87654321
- https://qaoffentlig.meldingsformidler.digipost.no/api/<databehandler>/<behandlingsansvarlig>

**Comment by asjafjell** [comment]
Hva tenker du om denne, @kagkarlsson? Vil dette fungere med Meldingsformidleren slik den er satt opp nå?

**Comment by aberner** [comment]
@asjafjell Det har blitt diskutert med dere og testet sammen med dere i testmiljøet allerede.
Ihvertfall så er den enkle varianten testet, med org.nummer til databehandler. Løsning for å få frem org.nummer både til behandling og dataansvarlig er ikke testet.

**Comment by kagkarlsson** [comment]
@asjafjell Ja, vi behöver inte göra några ändringar på server-sidan för att det ska fungera. Vi behöver dock göra ändringar för att kunna presentera mer information i meldingsformidler. Men det är en separat sak tänker jag.

@aberner Om det finns några integrationer på horisonten där behandlingansvarlig != dataansvarlig så borde vi kanske lägga upp till det i url-pattern från starten.

**Comment by aberner** [comment]
Ja vi har slike integrasjoner (behandlingansvarlig != dataansvarlig) på vei inn

**Comment by asjafjell** [comment]
Denne er utviklet og url blir på formatet: `{MF-Url}/{Databehandler}/{Avsender}` og vil bli slik uansett om det er samme organisasjon som er `Databehandler` og `Avsender` for å slippe den mentale mappingen når man leser urler. Er ute i _1.2.0-SNAPSHOT_
