### ISSUE TITLE
Avslutte støtte for java 1.6

### ISSUE THREAD

**Issue by landro** [difi/sikker-digital-post-klient-java#37]
Oracle avsluttet public support for java 1.6 i februar 2013. Ref http://www.oracle.com/technetwork/java/eol-135779.html avsluttes _Premier support_ i desember 2015.

Foreslår derfor at støtte for java 1.6 avsluttes i dette bibliotektet, og at minimum fra nå av blir versjon 1.7

**Comment by aberner** [comment]
Det er ok å avslutte støtte for java 1.6 i dette biblioteket.
Dersom alvorlige feil i klientbiblioteket mot formoding dukker opp vil de da kunne måtte håndteres ved at dagens versjon av klient-biblioteket patches. Difi har behov for å kunne gi støtte til avsender som brukere java 1.6 frem til og med april 2016 i produksjon.
Men ny funksjonalitet kan altså leveres i et klientbibliotek som ikke er basert på java 1.6.

er dette ok @landro ?

**Comment by aberner** [comment]
informasjon om denne endringen er lagt ut her: https://samarbeid.difi.no/nyheter/2015/11/digital-postkasse-til-innbyggere-java-klientbibliotek-vil-ikke-supportere-java-16-og (krever pålogging)

**Comment by asjafjell** [comment]
Dette er fikset i versjon [2.0.0](http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22sikker-digital-post-klient-java%22)
