### ISSUE TITLE
Avslutte støtte for java 1.7

### ISSUE THREAD

**Issue by landro** [difi/sikker-digital-post-klient-java#38]
Ref http://www.oracle.com/technetwork/java/eol-135779.html sluttet Oracle å utgi Public Updates for Oracle JDK 7 i april 2015.

Det er i tillegg en rekke nye interessante språk features i java 1.8, slik at det er ønskelig å avslutte støtte for java 1.7 så fort som mulig.

Java 9 er for øvrig etter planen tilgjengelig fra 2016-09-22

**Comment by aberner** [comment]
Det er ok å avslutte støtte for java 1.6 i dette biblioteket ref. #37 
Difi har ikke undersøkt avsenderes spesifikke behov for java 1.7.

Dersom alvorlige feil i klientbiblioteket mot formoding dukker opp vil de da kunne måtte håndteres ved at dagens versjon av klient-biblioteket patches. Difi har behov for å kunne gi støtte til avsender som brukere java 1.6 frem til og med april 2016 i produksjon. Fra og med april 2016 er planen for denne avsenderen å gå over på java 1.8.

Difi vil undersøke om det er behov for støtte for java 1.8 ved å sende ut informasjon til avsenderne om dette. På integrasjon og sikkerhetsforum 25. november vil vi også informere om dette og etter det forumet vil vi ha tilstrekkelig informasjon om Avsendere sitt behov for støtte på java 1.7.

Det vil si at vi kan ikke pr. dags dato avslutte støtten for java 1.7, men vi regner med å ha et grunnlag for dette 25. november slik at vi kan beslutte å avslutte støtte for dette kort tid etter det.

**Comment by aberner** [comment]
informasjon om denne endringen er lagt ut her: https://samarbeid.difi.no/nyheter/2015/11/digital-postkasse-til-innbyggere-java-klientbibliotek-vil-ikke-supportere-java-16-og (krever pålogging)

**Comment by landro** [comment]
Utmerket. Det er mildt sagt krevende å holde dette biblioteket oppdatert så lenge man fremdeles må forholde seg til 1.6.

**Comment by asjafjell** [comment]
Er det slik at det er ok å oppgradere til Java 1.8, @aberner, eller er det 1.7 som er ønskelig?

**Comment by aberner** [comment]
Det er avtalt at vi skal avslutte støtte for både java 1.6 og 1.7

**Comment by asjafjell** [comment]
Jeg ville bare forsikre meg. Takk for raskt svar!
