### ISSUE TITLE
Bekrefte kvittering med kun konversasjonsId?

### ISSUE THREAD

**Issue by tingstad** [difi/sikker-digital-post-klient-java#39]
Metodene SikkerDigitalPostKlient.bekreft() og hentKvitteringOgBekreftForrige() tar inn parameteret "forrigeKvittering" av type ForretningsKvittering.

Det betyr at ForretningsKvittering som returneres fra hentKvittering() må holdes i minnet helt til man vil bekrefte, og at hent() og bekreft() må skje "synkront" i en og samme applikasjonsinstans.

Vi ønsker å kunne kalle bekreft(String konversasjonsId) e.l. for å slippe denne begrensningen.

Da kan vi bruke sikker-digital-post-klient-java i frittstående applikasjon som kommuniserer med andre forretningssystem over f.eks. HTTP, og slik slippe sterk teknisk kobling mellom forretningssystem og sikker-digital-post-klient med avhengigheter. F.eks. kan de da enkelt kjøre på forskjellig plattform, Spring-versjon m.m.

**Comment by asjafjell** [comment]
Hva tenker du om denne, @kagkarlsson?

**Comment by asjafjell** [comment]
Nå er dette mulig ettersom `ForretningsKvittering` implementerer interfacet `KanBekreftesSomBehandletKvittering` i [2.1.0](http://search.maven.org/#artifactdetails%7Cno.difi.sdp%7Csikker-digital-post-klient-java%7C2.1.0%7Cjar)
