### ISSUE TITLE
Støtte for sending av flere dokumenter - ref versjon 1.2.4 av grensesnitt dokumentasjonen

### ISSUE THREAD

**Issue by aberner** [difi/sikker-digital-post-klient-java#56]
Klientbiblioteket må oppdatere XSD i henhold til versjon 1.2.4 av grensesnitt dokumentasjonen.
https://github.com/difi/begrep-SikkerDigitalPost/releases/tag/1.2.4

Dette for å kunne støtte sending av mer enn 10 vedlegg.

Endringen er planlagt realisert i løpet av desember 2016 i produksjon så klient biblioteket må ha en ny versjon med støtte for dette i god tid før dette.

**Comment by aberner** [comment]
jeg har behov for å få denne leveransen innen 11. november slik at vi kan få tid til å teste det ut og kunne være klare for funksjonell testing av e-boks, digipost og utskriftstjenesten.

**Comment by asjafjell** [comment]
Dette skal vi få til. Snakket tidligere i dag med @SimonsUnikaNamn og da ble det bekreftet at det er i rute. Vi må bare få gjort noen ytelsestester internt. Du får beskjed når dette er tilfelle, og det blir selvfølgelig før 11. november.

**Comment by oyri** [comment]
Me skal ta i bruk den nye versjonen 4.1.0 i difi testavsender, men ser at den berre ligg som ein release på github-prosjektet og ikkje i maven repository slik som føregåande artifacts. Kan de også deploye denne til maven repo (https://mvnrepository.com/artifact/no.difi.sdp/sikker-digital-post-java-klient)?

**Comment by asjafjell** [comment]
Den er deployet, men ligger under navnet _sikker-digital-post-klient-java_. Dette ble gjort om på for litt over et halvår siden. Du ser forskjellen hvis du søker på [sikker-digital-post](https://mvnrepository.com/search?q=%22sikker-digital-post-klient%22).

**Comment by asjafjell** [comment]
Jeg lukker denne siden det kom i produksjon i [v4.1.0](https://github.com/difi/sikker-digital-post-klient-java/releases/tag/4.1.0). Det er foreløbig kun støttet mot _difitest/qaoffentlig_, men fra et klientperspektiv er dette implementert, så jeg lukker bare denne.
