### ISSUE TITLE
Er patcha versjon av saaj nødvendig ved køyring av ytelsetestar?

### ISSUE THREAD

**Issue by oyri** [difi/sikker-digital-post-klient-java#61]
Ved køyring av ytelsetestar frå Testavsendaren legg me i dag til anna versjon av saaj-impl enn det som er pakka med sikker-digital-post-klient-java som kjem med versjon 1.3.23.
Me ekskluderer denne og legg heller ved denne: com.sun.xml.messaging.saaj:saaj-impl:1.3.26-SNAPSHOT etter anbefalling frå dykk (Stefan landrø) i okt 2014 pga alvorleg ytelseproblem i saaj. 

Eg ser at det har skjedd endringar både på https://github.com/digipost/saaj og https://github.com/gf-metro/saaj etter dette. Men ser ut som versjonen i sikker-digital-post-klient-java er uendra. 

Mitt spørsmål er om det er nødvendig å ekskludere denne lengre eller om f.eks. sikker-digital-post-klient-java kan ta i bruk ein nyare versjon?

Årsaka til at eg spør er fordi eg ynskjer å slå saman ytelsespesifikk branch med master i https://github.com/difi/sikker-digital-post-java-eksempel-webclient for å forenkle, om det er mogeleg. Dette er einaste skilnaden hos oss.

**Comment by asjafjell** [comment]
Dette kan kanskje @landro svare på?

**Comment by landro** [comment]
Det korte svaret, @oyri, er at ytelsestesten vil yte dårligere(du vil trenge flere cpu-er på last-generatorene), men det er ikke _nødvendig_.

**Comment by oyri** [comment]
OK, har de nokon plan om å oppdatere saaj versjon i sikker-digital-post-klient-java?

For vår del kan me sikkert bruke siste versjon frå https://github.com/digipost/saaj både for funksjonell testing og ytelsetesting.

**Comment by landro** [comment]
Nei. Det får være litt opp til den enkelt å avgjøre hvilken versjon man vil bruke. Dessuten kan det tenkes at man ikke trenger avhengigheten i det hele tatt, hvis man bruker en ny nok versjon av jdk-en (mem måten SAAJ kommer inn i jdk-en er rimelig krevende å forstå, og det er også vanskelig å vite hvilken versjon som brukes av jdk-en per default. Oracle patcher basert på support-henvendelser, og samtidig bytter de navnerom i det de shipper selv...)

**Comment by asjafjell** [comment]
Jeg lukker denne pga inaktivitet. Det er bare å åpne igjen @oyri om det er flere spørsmål knyttet til denne i framtiden 💯
