### ISSUE TITLE
Ønsker mulighet for å bruke forskjellige URL'r mot MF på sending av post og henting av kvitteringer

### ISSUE THREAD

**Issue by aberner** [difi/sikker-digital-post-klient-java#62]
ref: https://github.com/difi/sikker-digital-post-java-eksempel-webclient/issues/6

Vi ønsker å kunne bruke forskjellige URL'r mot MF når vi sender post og når vi henter kvitteringer.
Dette fordi vi ønsker en enkel måte å følge med på og skille de forskjellige requesten.

**Comment by aberner** [comment]
https://github.com/digipost/sdp-shared/issues/17

**Comment by rocketfarmsteinar** [comment]
Vi har sendt forespørsel til Digipost om denne, men forespørselen er enn så lenge ikkje svart. Har purra.

digipost/sdp-shared#17
