### ISSUE TITLE
Feilmeldinger i prodmiljøet, selv om alt ser ut til å fungere fint

### ISSUE THREAD

**Issue by mpuzar** [difi/sikker-digital-post-klient-java#63]
Hei,

Jeg får to forskjellige feil i prod-miljøet, men IKKE i verifikasjonsmiljøet. Først så trodde jeg det var pga at jeg brukte gammel klient (1.2.1), men ser nå samme oppførsel med 5.0.0.

1. Feil ved polling av kvitteringer:

Denne oppstår hver gang applikasjonen min poller for kvitteringer og det ikke er noe der. Tidligere var feilen litt mer utfyllende og sa bl.a. "Klarte ikke å verifisere signatur på responsen. Dette kan skyldes at det tiltrodde rotsertifikatet mangler i keystore/trust store. Hvis dette plutselig begynner å skje kan det skyldes at den andre parten har skiftet sertifikat". NB: Den klarer fint å parse kvitteringer når det faktisk er noe der.

```
2016.12.23 16:04:11.222 INFO  mf.logger.translog - [sender] [984661185] UTGÅENDE PULLREQUEST mpc:[urn:normal] conversationId:[] instanceId:[] messageId:[30d12337-531c-4826-a41b-9a76aeddde7c]  
2016.12.23 16:04:11.380 INFO  mf.logger.translog - [sender] [984661185] INNKOMMENDE TOMKØ mpc:[urn:normal] conversationId:[] instanceId:[] messageId:[6413f16e-e19c-4dc4-b983-57c11df2f8e1] ref:[30d12337-531c-4826-a41b-9a76aeddde7c] 
2016.12.23 16:04:11.452 ERROR no.fsat.fp.sdp.HentKvittering - Caught Exception while trying to fetch receipt
no.difi.sdp.client2.domain.exceptions.SendException: An unhandled exception occured while performing request
        at no.difi.sdp.client2.internal.DigipostMessageSenderFacade.performRequest(DigipostMessageSenderFacade.java:110) ~[sikker-digital-post-klient-java-5.0.0.jar:5.0.0]
        at no.difi.sdp.client2.internal.DigipostMessageSenderFacade.hentKvittering(DigipostMessageSenderFacade.java:82) ~[sikker-digital-post-klient-java-5.0.0.jar:5.0.0]
        at no.difi.sdp.client2.SikkerDigitalPostKlient.hentKvitteringOgBekreftForrige(SikkerDigitalPostKlient.java:91) ~[sikker-digital-post-klient-java-5.0.0.jar:5.0.0]
        at no.fsat.fp.sdp.HentKvittering.hentKvitteringOgBekreftForrige(HentKvittering.java:67) ~[classes/:na]
        at no.fsat.fp.sdp.HentKvittering.run(HentKvittering.java:52) ~[classes/:na]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_74]
Caused by: java.lang.IllegalArgumentException: null
        at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:247) ~[jaxb-impl-2.1.13.jar:2.1.13]
        at no.digipost.api.xml.Marshalling.unmarshal(Marshalling.java:134) ~[sdp-api-commons-1.2.0.jar:na]
        at no.digipost.api.handlers.ApplikasjonsKvitteringReceiver.extractData(ApplikasjonsKvitteringReceiver.java:52) ~[sdp-api-client-1.2.0.jar:na]
        at no.digipost.api.handlers.ApplikasjonsKvitteringReceiver.extractData(ApplikasjonsKvitteringReceiver.java:34) ~[sdp-api-client-1.2.0.jar:na]
        at org.springframework.ws.client.core.WebServiceTemplate.doSendAndReceive(WebServiceTemplate.java:619) ~[spring-ws-core-2.3.0.RELEASE.jar:2.3.0.RELEASE]
        at no.digipost.api.handlers.EbmsContextAwareWebServiceTemplate.doSendAndReceive(EbmsContextAwareWebServiceTemplate.java:60) ~[sdp-api-client-1.2.0.jar:na]
        at org.springframework.ws.client.core.WebServiceTemplate.sendAndReceive(WebServiceTemplate.java:555) ~[spring-ws-core-2.3.0.RELEASE.jar:2.3.0.RELEASE]
        at no.digipost.api.MessageSender$DefaultMessageSender.hentKvittering(MessageSender.java:366) ~[sdp-api-client-1.2.0.jar:na]
        at no.digipost.api.MessageSender.hentKvittering(MessageSender.java:63) ~[sdp-api-client-1.2.0.jar:na]
        at no.difi.sdp.client2.internal.DigipostMessageSenderFacade.lambda$hentKvittering$1(DigipostMessageSenderFacade.java:82) ~[sikker-digital-post-klient-java-5.0.0.jar:5.0.0]
        at no.difi.sdp.client2.internal.DigipostMessageSenderFacade.performRequest(DigipostMessageSenderFacade.java:103) ~[sikker-digital-post-klient-java-5.0.0.jar:5.0.0]
        ... 5 common frames omitted
```

2. (Tilsynelatende) feil ved sending

Når jeg forsøker å sende noe, kommer det alltid frem, men istedenfor å få vanlig LeveringsKvittering gir SikkerDigitalPostKlient.send() meg en SendException med innhold "An unhandled exception occured while performing request". 

Konkret eksempel (i tilfelle dere har nødvendige tilganger for å grave opp noe):
Tidspunkt: 2016-12-23 17:08:41
konversasjonsId: 9e937410-0e75-48a8-a625-cfc40264b5fb

Any ideas? Det som er mystisk er at a) alt fungerer finfint i testmiljøet, og b) alt ser ut til å fungere her også, bortsett fra disse exceptions som heller ikke hindrer posten fra å bli levert.

Hilsen,
Matija

**Comment by asjafjell** [comment]
Hei! Takk for svært god feilbeskrivelse. Vi tar tak i denne så snart det lar seg gjøre!

**Comment by asjafjell** [comment]
I tidligere versjoner av klienten (pre 5.0.0) så ville man få feilmeldingen _Klarte ikke å verifisere signatur på responsen …_ selv om trust store var satt opp riktig. I versjon 5.0.0 er dette fikset så denne feilmeldingen bare kommer når det er reelt. Jeg skulle gjerne visst hva du gjorde for å fikse dette, siden du sier _Tidligere var feilen litt mer utfyllende_. Ble det slik over natta eller gjorde du noe for å fikse det?

**Comment by mpuzar** [comment]
I tidligere versjon hadde jeg sertifikat-feilmeldingen. I 5.0.0 får jeg derimot ovennevnte SendException i stedet.

**Comment by asjafjell** [comment]
Dette er med stor sannsynlighet en feil i klienten. Har du mulighet til å lage en (Gist)(https://gist.github.com/) med kode som reproduserer problemet?

**Comment by mpuzar** [comment]
Her er det viktigste (tror jeg) fra klassen:
https://gist.github.com/mpuzar/66e3b88f26efb525f52c9d6ff3865349

**Comment by asjafjell** [comment]
Er det mulig for deg å hente ut issuer fra virksomhetssertifikatet dere bruker?

**Comment by mpuzar** [comment]
Owner: SERIALNUMBER=971035854, CN=FSAT, OU=FSAT, O=UNIVERSITETET I OSLO, C=NO
Issuer: CN=Buypass Class 3 CA 3, O=Buypass AS-983163327, C=NO
Serial number: 7f6a43e872fb7ca0fad93
Certificate fingerprints:
         MD5:  EB:AD:EC:D7:B4:2F:3A:26:19:81:9E:EE:8E:F4:36:DF
         SHA1: F8:0C:BB:19:8B:5A:8D:39:C6:C2:72:D5:57:C3:2B:09:94:84:DC:AE
         SHA256: DC:65:90:D6:0F:F1:FC:B4:B1:DC:97:C0:84:55:35:71:75:34:A0:0E:FF:66:C3:3B:E5:A6:23:18:A2:B1:C8:21
         Signature algorithm name: SHA256withRSA
         Version: 3

**Comment by mpuzar** [comment]
Som sagt så klarer den fint å hente en kvittering når det faktisk er noe å hente (f.eks med eBoks som alltid er tregere med å få levert ting).

**Comment by asjafjell** [comment]
Vi har en avsender som sender meg et ugyldig sertifikat selv om det er utstedt av en virksomhetsutsteder, og vet ikke i hvilken grad dette påvirker sending og validering, så ville bare se om det var deg. Det er det ikke. 

Kunne du sendt koden for hvordan du initierer `Noekkelpar` og databehandler? Husk å ta en ekstra sjekk på at du ikke sender med passord til sertifikat i gisten.

**Comment by asjafjell** [comment]
Kan du sende en ny melding mot prod som feiler og gi meg tidspunkt og konversasjonsid? Jeg finner noen feil i loggen etter din sending i går, men kan ikke bekrefte at det er knyttet til deg. Prøvde å sjekke rundt tidspunktet nevnt den 23. desember og der fant jeg dessverre ikke denne feilen.

**Comment by mpuzar** [comment]
Det er altså to vidt forskjellige typer feil det er snakk om (i hvert fall sett fra mitt ståsted):
1) Feil ved polling av kvitteringer - ingen konversasjonsId, det skjer hvert minutt
2) Feil ved sending - her kan vise til et superferskt eksempel: 2fbf4df7-d0ea-4fc8-a3e6-0920bfa50660, 2016-12-29 10:20:36

Ang. Nokkelpar, ikke mye hokus-pokus der. Her er en forkortet versjon av det som skjer:
```
keyStore.load(keystoreResource, keystorePass.toCharArray());
noekkelpar = Noekkelpar.fraKeyStore(keyStore, keyAlias, keyPass);
meldingsformidlerUri = "https://meldingsformidler.digipost.no/api/ebms";
klient = new SikkerDigitalPostKlient(Databehandler.builder(AktoerOrganisasjonsnummer.of("vårtorgnr".forfremTilDatabehandler(), noekkelpar).build(), KlientKonfigurasjon.builder(meldingsformidlerUri).build());
```

Iom. at alt ser ut til å fungere fint (dvs. posten kommer fram) så tyder ting på at problemet ligger på klientsiden, det er kanskje derfor du ikke finner noe på den andre siden. Det er SikkerDigitalPostKlient.java:50 (dvs. send()) som kaster SendException.

**Comment by asjafjell** [comment]
Beklager at det blir en del fisking her, men vi er ganske tynt bemannet i romjula (les: bare meg) og jeg har ikke stålkontroll på denne klienten. Det kan hende det er to vidt forskjellige feil, men du opplever dette kun i produksjonsmiljøet og ikke i test, og det eneste som er forskjellig mellom disse er sertifikater og eventuelle virksomhetsinnstillinger. Som du sier så kommer brevene gjennom, noe som tyder på at virksomhetsinnstillingene er satt opp riktig. Da står vi igjen med sertifikatlastingen. Jeg ser du bruker `Noekkelpar.fraKeyStore`. Har du husket å laste denne med produksjonssertifikater for Commfides og Buypass (rot og intermediate)?

**Comment by mpuzar** [comment]
Fisking er bedre enn ikke-fisking, så kjør på! :) Setter pris på all hjelp jeg kan få. Når det gjelder sertifikatene så spurte jeg Difi om det tidligere (nettopp fordi medlingen tidligere klagde på mangel på sertifikater) men fikk beskjed om at det ikke var nødvendig fordi "public key er en del av request og respons i meldingene". Så nei, jeg har ingen andre sertifikater i keystoren. Vet heller ikke hvor jeg skal få tak i dem, fant dem ikke i deres dokumentasjon (noe jeg sjekket detaljert før jeg sendte mail til Difi).

**Comment by mpuzar** [comment]
Oi oi, så det VAR det som manglet hele tiden... Takk, det gjorde susen!

Her tenker jeg at dokumentasjonen kan forbedres litt - informasjon om dette er veldig vanskelig å finne fra forsiden til dokumentasjonen (http://begrep.difi.no/SikkerDigitalPost/) med mindre man vet fra før hvordan man skal klikke seg fram dit.

Fint om dere også gir beskjed om det til kundestøtte (det var Ivar jeg først hadde fått svar fra om at det ikke var nødvendig).

Og igjen - takk for hjelpa!

**Comment by asjafjell** [comment]
Så flott at det fungerte! Det ble jammen litt famling i blinde, men fint å se at vi fant ut av det til slutt. 

Det er dokumentert [her i prosjektdokumentasjonen](https://difi.github.io/sikker-digital-post-klient-java/v4-5/#opprette-klient-og-sende-post) hvordan man kan bruke en keystore uten trust store. Dette aktiverer trust store internt i klienten og gjør at du slipper å lage en slik store selv, men jeg så når jeg hjalp deg at denne ikke støtter produksjonsmiljøet. Dette har jeg opprettet et issue på (#65). Når det er sagt så kan info om sertifikater godt ligge mer tilgjengelig både i dokumentasjonen til Difi og for klientbiblioteket. Feilhåndteringen når en slik store er feilinitialisert er i beste fall litt kjip.

Fortsatt god jul! 🎅🏽🎄
