### ISSUE TITLE
Tilgang til WebServiceTemplate

### ISSUE THREAD

**Issue by FrodeBjerkholt** [difi/sikker-digital-post-klient-java#81]
Vi har behov for kunne mocke WebService-kallet i sikker-digital-post-klient. For å gjøre det på enkel måte, så trenger vi tilgang til WebServiceTemplate. Jeg har laget [pull-request](https://github.com/difi/sikker-digital-post-klient-java/pull/80).

**Comment by runeflobakk** [comment]
Fikset i versjon 5.5
Bør dukke opp i Maven Central om ikke så lenge, når [denne lenken](https://search.maven.org/remotecontent?filepath=no/difi/sdp/sikker-digital-post-klient-java/5.5/sikker-digital-post-klient-java-5.5.pom) ikke gir 404
